### Урок 8. Вебинар “Введение в линейную алгебру”#

### -- Автор: Шенк Евгений Станиславович

In [1]:
import math
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline

### Задание 1. Решите линейную систему:

In [2]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
X = np.linalg.solve(A, B)
X

array([-9.2       ,  0.9       ,  6.46666667])

### Задание 2. Найдите псевдорешение:

In [3]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
X = np.linalg.lstsq(A, B)[0]
X

array([ 1.13919353, -0.90498444, -0.9009803 ])

In [4]:
np.dot(A, X)

array([ 0.23020495,  7.03751834, 11.83650981,  6.78328855, 15.21805313])

### Задание 3. Сколько решений имеет линейная система:
### Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее.

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
X = np.linalg.solve(A, B)

print(X)

[ 2.83726777e+16 -5.67453553e+16  2.83726777e+16]


##### Получился ноль

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([3, 2, 1])
X = np.linalg.solve(A, B)

print(X)

[ 0.33333333 -4.66666667  4.        ]


In [7]:
np.dot(A, X)

array([3., 2., 1.])

### Задание 4. Вычислите LU-разложение матрицы:
### После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [8]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])

In [9]:
P, L, U = la.lu(A)

In [10]:
print(P)
print(L)
print(U)

print(A - np.dot(np.dot(P , L ), U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
B = np.array([4, 7, 13])

In [12]:
Y = np.linalg.solve(np.dot(P, L), B)
Y

array([13.  ,  0.75,  0.8 ])

In [13]:
X = np.linalg.solve(U, Y)
X

array([ 4.18518519, -0.03703704, -0.03703704])

### Проверка

In [14]:
X_2 = np.linalg.solve(A, B)
X_2

array([ 4.18518519, -0.03703704, -0.03703704])

In [15]:
np.dot(A, X)

array([ 4.,  7., 13.])

In [16]:
np.dot(A, X_2)

array([ 4.,  7., 13.])

### Задание 5. Найдите нормальное псевдорешение недоопределенной системы:
### Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум.
### x + 2y – z = 1
#### 8x – 5y + 2z = 12

In [17]:
A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([1, 12])

##### z = -1 + x + 2y
##### 10x - y = 14
##### y = -14 + 10x
##### Берем любые подходящие для определения прямой
##### x = 1
##### y = -4
##### z = -8

In [18]:
def Q (x, y, z):
    return (x**2 + y**2 + z**2, x, y, z)

In [19]:
L = np.cross(A[0], A[1])
L

array([ -1, -10, -21])

##### Определяем прямую
##### x-1 / (-1) = y+4 / (-10) = z+8 / (-21)

In [20]:
X_1 = np.linspace(-5, 5, 20001)

q = []

for x in X_1:
    q.append(Q(x, 10 * (x - 1) - 4, 21 * (x - 1) - 8))
min(q, key=lambda x: x[0])

(1.942808, 1.3820000000000006, -0.1799999999999944, 0.022000000000012676)

### Получилось: [1.382, -0.180, 0.022]

In [21]:
# Проверка
a = np.array([[1, 2, -1], [8, -5, 2]])
b = np.array([1, 12])
np.linalg.lstsq(a, b)

(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

### Задание 6. Найдите одно из псевдорешений вырожденной системы:
### Попробуйте также отыскать и нормальное псевдорешение.

In [22]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])

In [23]:
np.linalg.lstsq(A, B)

(array([ 1.25,  0.5 , -0.25]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]))

In [24]:
Q, R = np.linalg.qr(A)

In [25]:
print(Q)
print(R)

[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]


In [26]:
R1 = R[:2,:2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [27]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  8.54871729e-15])

In [28]:
X1 = np.linalg.solve(R1,B1)
X1

array([1.50000000e+00, 9.45096256e-15])

In [29]:
X = np.append(X1, 0)
print(X)
np.linalg.norm(X)

[1.50000000e+00 9.45096256e-15 0.00000000e+00]


1.4999999999999893

In [30]:
R2 = R[:2,2]
R2

array([-11.07823419,   1.80906807])

In [31]:
def Q(x_0, x_1, x_2):
    return(x_0**2 + x_1**2 + x_2**2, np.linalg.norm([x_0, x_1, x_2]), x_0, x_1, x_2)

In [32]:
x_2 = np.arange(-10, 10, 0.01)

q = []

for i in x_2:
    X1 = np.linalg.solve(R1, (B1 - (R2 * i)))
    x_0 = np.sum((X1[0:2])[0])
    x_1 = np.sum((X1[0:2])[1])
    q.append(Q(x_0, x_1, i))
    
min(q, key=lambda x: x[0])

(1.874999999999984,
 1.3693063937629095,
 1.2499999999997824,
 0.5000000000004242,
 -0.25000000000020783)

### Получилось: [1.25, 0.5, -0.25]

In [33]:
X = np.array([1.25,  0.5 , -0.25])
np.linalg.norm(X), np.linalg.norm(np.dot(A, X) - B)

(1.3693063937629153, 1.224744871391589)

In [34]:
np.linalg.lstsq(A, B)

(array([ 1.25,  0.5 , -0.25]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]))